CREATE TABLE Users (
Username VARCHAR(16) NOT NULL,
Password VARCHAR(16) NOT NULL,
PRIMARY KEY(Username)
);

CREATE TABLE Questions(
ID INT,
Text VARCHAR(420) NOT NULL,
Author VARCHAR(16),
PRIMARY KEY(ID),
FOREIGN KEY (Author) REFERENCES Users(Username)
);

CREATE TABLE Answers(
ID INT,
Text VARCHAR(420) NOT NULL,
Question VARCHAR(420) NOT NULL,
Author VARCHAR(16) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (Question) REFERENCES Questions(ID),
FOREIGN KEY (Author) REFERENCES Users(Username)
);